### PR TITLE
Sign flash after code has been verified.

### PR DESCRIPTION
**Pull request by mickeprag**
After the flash has been verified we need to send the SIGN_FLASH command
to the bootloader. Else the bootloader won't boot into the new firmware.

### CODE REVIEW

**Comment by AdamLaurie** [comment]
What version of bootloader are you running (and where does the source live?)? I do not believe the current version that we are testing against supports this command.

**Comment by mickeprag** [comment]
I am using MLA version v2015-08-10 downloadable here:
http://www.microchip.com/mplab/microchip-libraries-for-applications

**Comment by AdamLaurie** [comment]
Great, thanks. I think you need to modify it so it doesn't give an error when used against older versions that do not support this command. Possibly it could flag that a bootloader upgrade is suggested?

**Comment by mickeprag** [comment]
I don't have the code for an older bootloader but in current the code for handling and unknown commands looks like this (code removed for clarity):

    //Check the latest command we received from the PC app, to determine what
    //we should be doing.
    switch(PacketFromPC.Command)
    {
        case QUERY_DEVICE:
        case UNLOCK_CONFIG:
        case ERASE_DEVICE:
        case PROGRAM_DEVICE:
        case PROGRAM_COMPLETE:
        case GET_DATA:
        case SIGN_FLASH:
        case RESET_DEVICE:
        default:
            //Should never hit the default
            BootState = IDLE;
    }//End switch

This means an unknown command will be silently ignored and mphidflash won't know when to print a warning or not.

**Comment by AdamLaurie** [comment]
The older version has no default statement, so I suspect the outcome will be that the process hangs as BootState will be left in NotIdleState. I guess the simplest way to find out is to test it, so I'll do so...

**Comment by AdamLaurie** [comment]
Yes, as suspected, the bootloader is left in a busy state so further commands are ignored. This is not a big deal, but will mean a reset fails if requested. That gives us three options:

1. Make it an option that must be specified if required (default is OFF).

2. Make it an option that must be disabled if not required (default is ON).

3. Send the command regardless, but inform the user of the potential problem. I would suggest the sign output should say something like "Signing flash... (Warning: Older bootloaders may become non-responsive. Manual reset will be required!)" - the only issue here is if it's confusing enough for them then to not be sure if the flash itself was successful?

**Comment by mickeprag** [comment]
My vote goes for option number 1. This willl not break installations if the tool is embedded in some system.

**Pull request merged**
