### PR TITLE
Call PROGRAM_COMPLETE if the last block is the last one in the section.

### PR DESCRIPTION
**Pull request by mickeprag**
See #18

### CODE REVIEW

**Comment by AdamLaurie** [comment]
This results in multiple duplicate calls to PROGRAM_COMPLETE. Please try this patch instead which I believe should only call it for the explicit case when final section was exactly 56 bytes:

diff --git a/hex.c b/hex.c
index 59ff6d7..399b9ad 100644
--- a/hex.c
+++ b/hex.c
@@ -319,6 +319,8 @@ ErrorCode hexWrite(const char verify)
                if(bufLen) {
                  if(ERR_NONE != (status = issueBlock(addrSave,bufLen,pass)))
                    return status;
+                 if(bufLen == 56 && ERR_NONE != (status = issueBlock(addrSave,0,pass)))
+                   return status;
                  bufLen = 0;
                }
                addrSave = addr32;

Apologies that I can't test it myself, but a negative test looks correct for the opposite case...

**Comment by AdamLaurie** [comment]
`diff --git a/hex.c b/hex.c
index 59ff6d7..399b9ad 100644
--- a/hex.c
+++ b/hex.c
@@ -319,6 +319,8 @@ ErrorCode hexWrite(const char verify)
                if(bufLen) {
                  if(ERR_NONE != (status = issueBlock(addrSave,bufLen,pass)))
                    return status;
+                 if(bufLen == 56 && ERR_NONE != (status = issueBlock(addrSave,0,pass)))
+                   return status;
                  bufLen = 0;
                }
                addrSave = addr32;
`

**Comment by mickeprag** [comment]
Your patch above does unfortunately not work. The (last) call to issueBlock is the one on line 332, not 320. Your addition should be added for that issueBlock instead. But here the bufLen is very often 56 bytes so it would call PROGRAM_COMPLETE almost on every block.

My pull request above only calls PROGRAM_COMPLETE one extra time for my firmware.

**Comment by mickeprag** [comment]
Just a clarification:
issueBlock on line 320 is called on the _first_ block in the section.
issueBlock on line 332 is called on the rest including the last one where we need the extra PROGRAM_COMPLETE.

**Comment by AdamLaurie** [comment]
Strange. Writing RFIDLer standard firmware calls PROGRAM_COMPLETE 217 times with the existing code. With your patch it is 391. It probably doesn't matter, but I'd prefer that we hunt down the correct time to apply it so we only do so once! :)

**Comment by mickeprag** [comment]
I am all for hunting it down to fix it correctly. My project has a deadline so I will apply my patch in our system until the correct fix is in place.
Would it help you if I send you my firmware I am trying to flash? It is for PIC18F25K50 but since this is actually a logical issue it should not matter.

**Comment by AdamLaurie** [comment]
Yes, please do. Thanks for your patience and your contributions.

**Comment by AdamLaurie** [comment]
OK, here is a patch which takes a simplified approach: we always "complete" before starting a new block, and again once at the end. This should catch all cases and is easy to follow. If you have time please test it against your hex file. It works fine with my images.

[patch1.gz](https://github.com/ApertureLabsLtd/mphidflash/files/263474/patch1.gz)

**Comment by mickeprag** [comment]
Hmm, this did not work.
But, from the output it seems it is issuing the program complete correctly...
Output is attached
[out.txt](https://github.com/ApertureLabsLtd/mphidflash/files/263504/out.txt)

**Comment by mickeprag** [comment]
For comparison, here is the output from the patch in my pull request.
[outok.txt](https://github.com/ApertureLabsLtd/mphidflash/files/263508/outok.txt)

**Comment by AdamLaurie** [comment]
My bad, I had accidentally switched off verification during my test... Please try this one:

[patch2.gz](https://github.com/ApertureLabsLtd/mphidflash/files/263603/patch2.gz)

**Comment by AdamLaurie** [comment]
Sorry, having one of those days! Logic was back to front there... This should be correct:

[patch3.gz](https://github.com/ApertureLabsLtd/mphidflash/files/263663/patch3.gz)

**Comment by mickeprag** [comment]
I can verify that patch3 works. At least the verification passes.

**Comment by AdamLaurie** [comment]
Committed my version - thanks for your help!

**Pull request closed without merging**
